name: Docker Development Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOCKER_IMAGE: ardialqlause/personal-landing-page

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.prod
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:prod
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 92.113.145.8 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh ardial@92.113.145.8 '
            # Switch to root user and execute commands
            sudo bash -c "
              # Pull the latest image
              docker pull ${{ env.DOCKER_IMAGE }}:prod
              
              # Stop and remove all containers if any exist
              if [ \$(docker ps -aq | wc -l) -gt 0 ]; then
                docker stop \$(docker ps -aq)
                docker rm \$(docker ps -aq)
              fi
              
              # Kill any process using port 3000
              lsof -ti:3000 | xargs kill -9 2>/dev/null || true
              
              # Run the new container
              docker run -d \
                --restart unless-stopped \
                -p 127.0.0.1:3000:3000 \
                ${{ env.DOCKER_IMAGE }}:prod
            "
          '
